#Tune these settings for "offline" (no DB), so to measure the overhead of Quarkus & Hibernate processing only:
quarkus.datasource.devservices.enabled=true
quarkus.datasource.jdbc.max-size=5
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.initial-size=0
quarkus.hibernate-orm.database.start-offline=true
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.log.category."org.hibernate.orm.deprecation".level=OFF
